#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace App;

use Timesplinter\Oyster\Command\CdCommandInterface;
use Timesplinter\Oyster\Console;
use Timesplinter\Oyster\Executor;
use Timesplinter\Oyster\Command\PwdCommandInterface;
use Timesplinter\Oyster\Helper\NullHistory;
use Timesplinter\Oyster\History\ReadlineHistory;
use Timesplinter\Oyster\Input\ReadlineInput;
use Timesplinter\Oyster\Input\StdInInput;
use Timesplinter\Oyster\OperatingSystemAdapter\DarwinAdapter;
use Timesplinter\Oyster\OperatingSystemAdapter\LinuxAdapter;

require __DIR__ . '/vendor/autoload.php';

$builtinCommands = [
    new PwdCommandInterface(),
    new CdCommandInterface()
];

$executor = new Executor();

if ('Darwin' === PHP_OS) {
    $osAdapter = new DarwinAdapter($executor);
} elseif ('Linux' === PHP_OS) {
    $osAdapter = new LinuxAdapter($executor);
} else {
    echo "Operating system currently not supported: ".PHP_OS."\n";
    exit;
}

if(true === function_exists('readline')) {
    $history = new ReadlineHistory();
    $input = new ReadlineInput();
} else {
    $history = new NullHistory();
    $input = new StdInInput();
    echo "INFO: You're PHP binary isn't compiled with readline support.\n";
}

$console = new Console($input, $osAdapter, $builtinCommands, $executor, $history);
$console->run();
